id: IBE7ADF43
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:13:47+00:00'
last_modified: '2022-06-08T06:00:26.110128+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8871
  title: དྲི་བ་རྣམ་པར་རྒྱལ་བའི་དྲིས་ལན་ལུང་རིག་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    904D:
      image_group_id: I1931
      title: ''
      total_pages: 53
      order: 1
      base_file: 904D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
